import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Widget bundle output (Vite minified) — not source.
    // ESLint flags every keepNames `s(name, "name")` call as a
    // no-unused-expression. Adding the rule locally would be
    // heavier than ignoring the file.
    "public/widget.js",
    // @markup/core package build output (generated by tsc) — not source.
    "packages/*/dist/**",
  ]),
  {
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-require-imports': 'off',
      'react/no-unescaped-entities': 'off',
      'react-hooks/purity': 'off',
      'react-hooks/set-state-in-effect': 'off',
    },
  },
]);

export default eslintConfig;
